name: Trusted Partner PR
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  assign-partner-tags:
    runs-on: ubuntu-latest
    permissions:
      # Needed to attach tags into the PR
      issues: write
      contents: write
      pull-requests: write
    if: |
      github.event.pull_request.draft == false &&
      github.event.sender.type == 'User'
    steps:
      - name: Checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Trusted-Partners-PR
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # v6.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/workflows/trusted_partners.js');
            require('./test.js');
            const username = context.payload.pull_request.user.login;
            const domain = await script.get_email_domain({github, username});
            switch(domain) {
            case "intel.com":
              console.log(await script.filter({github, context, domain}));
              break;
            case "apple.com":
              console.log(await script.filter({github, context, domain}));
              break;
            case "nvidia.com":
              console.log(await script.filter({github, context, domain}));
              break;
            case "linaro.org":
              console.log(await script.filter({github, context, domain}));
              break;
            case "arm.com":
              console.log(await script.filter({github, context, domain}));
              break;
            case "google.com":
              console.log("Googler. No action necessary");
              break;
            default:
              console.log("Skip Trusted Partner Action");
            }
